version: '3.4'
services:
  postgres:
    build: ./docker/postgres
    networks:
      - backend
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/postgres:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  puppeteer:
    build: ./docker/puppeteer
    env_file:
      - .env.docker
    networks:
      - backend
    restart: on-failure
    volumes:
      - ${PWD}/puppeteer/dist:/code
    command: node index.js
    depends_on:
      - postgres

  apiclient:
    build: ./docker/service
    env_file:
      - .env.docker
    networks:
      - backend
    restart: on-failure
    volumes:
      - ${PWD}/service/dist:/code
    command: node index.js
    depends_on:
      - postgres

networks:
  backend:
    driver: bridge
